del KefAirportFlug\kvl.exe
del KefAirportFlug\komur
del KefAirportFlug\out.fly
del newKAF\komur
del newKAF\brottfarir
del newKAF\out.fly
del newKAF\inn.fly
del newKAF\charlone.exe
del oldKAF.lnk
del KAF.lnk
del newKAF.lnk
